server:
  port: 8002

spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  cloud:
    stream:
      bindings:
        output:
          destination: menu

#      kafka:
#        binder:
#          zkNodes: localhost
#          brokers: localhost
